# Generated by Django 4.2.16 on 2025-09-25 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collaboration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=2000)),
                ("goals", models.TextField(blank=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("target_completion", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "collaborations",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("on_hold", "On Hold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("progress_percentage", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("estimated_hours", models.PositiveIntegerField(blank=True, null=True)),
                ("actual_hours", models.PositiveIntegerField(default=0)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("allow_file_sharing", models.BooleanField(default=True)),
                ("enable_time_tracking", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_projects",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-last_activity_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("review", "In Review"),
                            ("done", "Done"),
                        ],
                        default="todo",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("estimated_hours", models.PositiveIntegerField(blank=True, null=True)),
                ("actual_hours", models.PositiveIntegerField(default=0)),
                ("board_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to="accounts.creatorprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to="accounts.creatorprofile",
                    ),
                ),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blocking_tasks",
                        to="collaborations.task",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="collaborations.project",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["board_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_comments",
                        to="accounts.creatorprofile",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="collaborations.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMilestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("due_date", models.DateTimeField()),
                ("completion_percentage", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_milestones",
                        to="accounts.creatorprofile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="collaborations.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_milestones",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("can_edit_project", models.BooleanField(default=False)),
                ("can_manage_tasks", models.BooleanField(default=True)),
                ("can_upload_files", models.BooleanField(default=True)),
                ("can_invite_members", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to="accounts.creatorprofile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="collaborations.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_memberships",
            },
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="project_files/%Y/%m/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("archive", "Archive"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("file_size", models.PositiveIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_public", models.BooleanField(default=False)),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "virus_scan_status",
                    models.CharField(default="pending", max_length=20),
                ),
                ("virus_scan_result", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newer_versions",
                        to="collaborations.projectfile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="collaborations.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="collaborations.task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "project_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewCollaborationInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_title", models.CharField(max_length=200)),
                (
                    "project_brief",
                    models.TextField(
                        help_text="Detailed description of the collaboration"
                    ),
                ),
                (
                    "scope_of_work",
                    models.TextField(help_text="Specific tasks and deliverables"),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("estimated_hours", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "compensation_type",
                    models.CharField(
                        choices=[
                            ("none", "No Compensation"),
                            ("fixed", "Fixed Amount"),
                            ("hourly", "Hourly Rate"),
                            ("revenue_share", "Revenue Share"),
                            ("equity", "Equity"),
                            ("barter", "Barter/Trade"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "compensation_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "compensation_currency",
                    models.CharField(default="USD", max_length=3),
                ),
                (
                    "compensation_details",
                    models.TextField(
                        blank=True, help_text="Additional compensation details"
                    ),
                ),
                ("nda_required", models.BooleanField(default=False)),
                (
                    "nda_document",
                    models.FileField(blank=True, null=True, upload_to="ndas/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("countered", "Countered"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Personal message with the invite"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("response_message", models.TextField(blank=True)),
                ("counter_offer_details", models.JSONField(blank=True, default=dict)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "new_collaboration_invites",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InviteTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("project_title_template", models.CharField(max_length=200)),
                ("project_brief_template", models.TextField()),
                ("scope_of_work_template", models.TextField()),
                ("scope_template", models.TextField()),
                ("message_template", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_compensation_type",
                    models.CharField(
                        choices=[
                            ("none", "No Compensation"),
                            ("fixed", "Fixed Amount"),
                            ("hourly", "Hourly Rate"),
                            ("revenue_share", "Revenue Share"),
                            ("equity", "Equity"),
                            ("barter", "Barter/Trade"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("default_nda_required", models.BooleanField(default=False)),
                ("default_duration_days", models.PositiveIntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "invite_templates",
                "ordering": ["-usage_count", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CollaborationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("review", "Under Review"),
                            ("completed", "Completed"),
                        ],
                        default="todo",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_collaboration_tasks",
                        to="accounts.creatorprofile",
                    ),
                ),
                (
                    "collaboration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="collaborations.collaboration",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_collaboration_tasks",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "collaboration_tasks",
            },
        ),
        migrations.CreateModel(
            name="CollaborationInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=1000)),
                ("collaboration_type", models.CharField(max_length=50)),
                ("match_explanation", models.TextField(blank=True, max_length=500)),
                ("match_score", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites_received",
                        to="accounts.creatorprofile",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites_sent",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "collaboration_invites",
            },
        ),
        migrations.CreateModel(
            name="CollaborationFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="collaboration_files/%Y/%m/")),
                ("file_type", models.CharField(max_length=50)),
                ("file_size", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True, max_length=500)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collaboration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="collaborations.collaboration",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "collaboration_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="collaboration",
            name="invite",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaboration",
                to="collaborations.collaborationinvite",
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="participants",
            field=models.ManyToManyField(
                related_name="collaborations", to="accounts.creatorprofile"
            ),
        ),
        migrations.CreateModel(
            name="AICollaborationSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("portfolio_match", "Portfolio Match"),
                            ("skill_complement", "Skill Complement"),
                            ("style_similarity", "Style Similarity"),
                            ("location_based", "Location Based"),
                        ],
                        max_length=20,
                    ),
                ),
                ("match_score", models.FloatField()),
                ("explanation", models.TextField(max_length=500)),
                ("suggested_project_type", models.CharField(max_length=100)),
                ("suggested_title", models.CharField(max_length=200)),
                ("suggested_description", models.TextField(max_length=1000)),
                ("is_viewed", models.BooleanField(default=False)),
                ("is_acted_upon", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_suggestions",
                        to="accounts.creatorprofile",
                    ),
                ),
                (
                    "suggested_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_for",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ai_collaboration_suggestions",
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "status"], name="tasks_project_fe19a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assignee", "status"], name="tasks_assigne_972e70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["due_date"], name="tasks_due_dat_0359a9_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["board_order"], name="tasks_board_o_a10eca_idx"),
        ),
        migrations.AddIndex(
            model_name="projectmilestone",
            index=models.Index(
                fields=["project", "status"], name="project_mil_project_bc846a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmilestone",
            index=models.Index(
                fields=["due_date"], name="project_mil_due_dat_c8bee4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["project", "role"], name="project_mem_project_ce1662_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectmembership",
            unique_together={("project", "member")},
        ),
        migrations.AddIndex(
            model_name="projectfile",
            index=models.Index(
                fields=["project", "file_type"], name="project_fil_project_2531b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectfile",
            index=models.Index(
                fields=["uploaded_by", "created_at"],
                name="project_fil_uploade_46e320_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["status", "priority"], name="projects_status_b3b152_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["owner", "status"], name="projects_owner_i_597fe2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["last_activity_at"], name="projects_last_ac_c42588_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newcollaborationinvite",
            index=models.Index(
                fields=["from_user", "status"], name="new_collabo_from_us_4e6659_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newcollaborationinvite",
            index=models.Index(
                fields=["to_user", "status"], name="new_collabo_to_user_e75c53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newcollaborationinvite",
            index=models.Index(
                fields=["status", "expires_at"], name="new_collabo_status_4813d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationtask",
            index=models.Index(
                fields=["assigned_to", "status"], name="collaborati_assigne_0429f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationtask",
            index=models.Index(
                fields=["collaboration", "status"],
                name="collaborati_collabo_853041_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationinvite",
            index=models.Index(
                fields=["status", "created_at"], name="collaborati_status_429d0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationinvite",
            index=models.Index(
                fields=["recipient", "status"], name="collaborati_recipie_5feec3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collaborationinvite",
            unique_together={("sender", "recipient", "title")},
        ),
        migrations.AddIndex(
            model_name="collaboration",
            index=models.Index(
                fields=["status", "created_at"], name="collaborati_status_a30572_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aicollaborationsuggestion",
            index=models.Index(
                fields=["profile", "match_score"], name="ai_collabor_profile_908b85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aicollaborationsuggestion",
            index=models.Index(
                fields=["created_at"], name="ai_collabor_created_d7612d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aicollaborationsuggestion",
            unique_together={("profile", "suggested_profile")},
        ),
    ]
