# Generated by Django 4.2.16 on 2025-08-16 20:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collaboration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=2000)),
                ("goals", models.TextField(blank=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("target_completion", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "collaborations",
            },
        ),
        migrations.CreateModel(
            name="CollaborationInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=1000)),
                ("collaboration_type", models.CharField(max_length=50)),
                ("match_explanation", models.TextField(blank=True, max_length=500)),
                ("match_score", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites_received",
                        to="accounts.creatorprofile",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites_sent",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "collaboration_invites",
            },
        ),
        migrations.CreateModel(
            name="CollaborationFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="collaboration_files/%Y/%m/")),
                ("file_type", models.CharField(max_length=50)),
                ("file_size", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True, max_length=500)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collaboration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="collaborations.collaboration",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "collaboration_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="collaboration",
            name="invite",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaboration",
                to="collaborations.collaborationinvite",
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="participants",
            field=models.ManyToManyField(
                related_name="collaborations", to="accounts.creatorprofile"
            ),
        ),
        migrations.CreateModel(
            name="AICollaborationSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("portfolio_match", "Portfolio Match"),
                            ("skill_complement", "Skill Complement"),
                            ("style_similarity", "Style Similarity"),
                            ("location_based", "Location Based"),
                        ],
                        max_length=20,
                    ),
                ),
                ("match_score", models.FloatField()),
                ("explanation", models.TextField(max_length=500)),
                ("suggested_project_type", models.CharField(max_length=100)),
                ("suggested_title", models.CharField(max_length=200)),
                ("suggested_description", models.TextField(max_length=1000)),
                ("is_viewed", models.BooleanField(default=False)),
                ("is_acted_upon", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_suggestions",
                        to="accounts.creatorprofile",
                    ),
                ),
                (
                    "suggested_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_for",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ai_collaboration_suggestions",
            },
        ),
        migrations.CreateModel(
            name="CollaborationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("review", "Under Review"),
                            ("completed", "Completed"),
                        ],
                        default="todo",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tasks",
                        to="accounts.creatorprofile",
                    ),
                ),
                (
                    "collaboration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="collaborations.collaboration",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "collaboration_tasks",
                "indexes": [
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="collaborati_assigne_0429f7_idx",
                    ),
                    models.Index(
                        fields=["collaboration", "status"],
                        name="collaborati_collabo_853041_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="collaborationinvite",
            index=models.Index(
                fields=["status", "created_at"], name="collaborati_status_429d0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationinvite",
            index=models.Index(
                fields=["recipient", "status"], name="collaborati_recipie_5feec3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collaborationinvite",
            unique_together={("sender", "recipient", "title")},
        ),
        migrations.AddIndex(
            model_name="collaboration",
            index=models.Index(
                fields=["status", "created_at"], name="collaborati_status_a30572_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aicollaborationsuggestion",
            index=models.Index(
                fields=["profile", "match_score"], name="ai_collabor_profile_908b85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aicollaborationsuggestion",
            index=models.Index(
                fields=["created_at"], name="ai_collabor_created_d7612d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aicollaborationsuggestion",
            unique_together={("profile", "suggested_profile")},
        ),
    ]
