# Generated by Django 4.2.16 on 2025-08-20 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collaborations", "0002_project"),
    ]

    operations = []
