# Generated by Django 5.1.4 on 2024-12-19 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0003_auto_20250820_0819'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCollaborationInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=200)),
                ('project_brief', models.TextField(help_text='Detailed description of the collaboration')),
                ('scope_of_work', models.TextField(help_text='Specific tasks and deliverables')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('compensation_type', models.CharField(choices=[('none', 'No Compensation'), ('fixed', 'Fixed Amount'), ('hourly', 'Hourly Rate'), ('revenue_share', 'Revenue Share'), ('equity', 'Equity'), ('barter', 'Barter/Trade')], default='none', max_length=20)),
                ('compensation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('compensation_currency', models.CharField(default='USD', max_length=3)),
                ('compensation_details', models.TextField(blank=True, help_text='Additional compensation details')),
                ('nda_required', models.BooleanField(default=False)),
                ('nda_document', models.FileField(blank=True, null=True, upload_to='ndas/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('countered', 'Countered'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Personal message with the invite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True)),
                ('counter_offer_details', models.JSONField(blank=True, default=dict)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'new_collaboration_invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InviteTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('project_title_template', models.CharField(max_length=200)),
                ('project_brief_template', models.TextField()),
                ('scope_of_work_template', models.TextField()),
                ('scope_template', models.TextField()),
                ('message_template', models.TextField(blank=True)),
                ('default_compensation_type', models.CharField(choices=[('none', 'No Compensation'), ('fixed', 'Fixed Amount'), ('hourly', 'Hourly Rate'), ('revenue_share', 'Revenue Share'), ('equity', 'Equity'), ('barter', 'Barter/Trade')], default='none', max_length=20)),
                ('default_nda_required', models.BooleanField(default=False)),
                ('default_duration_days', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invite_templates',
                'ordering': ['-usage_count', '-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='newcollaborationinvite',
            index=models.Index(fields=['from_user', 'status'], name='new_collabo_from_us_4b3b63_idx'),
        ),
        migrations.AddIndex(
            model_name='newcollaborationinvite',
            index=models.Index(fields=['to_user', 'status'], name='new_collabo_to_user_b5e8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='newcollaborationinvite',
            index=models.Index(fields=['status', 'expires_at'], name='new_collabo_status_c8b9c6_idx'),
        ),
    ]
