# Generated by Django 4.2.16 on 2025-08-20 08:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_premiumaddon_subscriptionplan_usersubscription_and_more"),
        ("collaborations", "0004_add_invitation_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="project_files/%Y/%m/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("archive", "Archive"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("file_size", models.PositiveIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_public", models.BooleanField(default=False)),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "virus_scan_status",
                    models.CharField(default="pending", max_length=20),
                ),
                ("virus_scan_result", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "project_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("can_edit_project", models.BooleanField(default=False)),
                ("can_manage_tasks", models.BooleanField(default=True)),
                ("can_upload_files", models.BooleanField(default=True)),
                ("can_invite_members", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "project_memberships",
            },
        ),
        migrations.CreateModel(
            name="ProjectMilestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("due_date", models.DateTimeField()),
                ("completion_percentage", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "project_milestones",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("review", "In Review"),
                            ("done", "Done"),
                        ],
                        default="todo",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("estimated_hours", models.PositiveIntegerField(blank=True, null=True)),
                ("actual_hours", models.PositiveIntegerField(default=0)),
                ("board_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["board_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "task_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-last_activity_at"]},
        ),
        migrations.RenameIndex(
            model_name="newcollaborationinvite",
            new_name="new_collabo_from_us_4e6659_idx",
            old_name="new_collabo_from_us_4b3b63_idx",
        ),
        migrations.RenameIndex(
            model_name="newcollaborationinvite",
            new_name="new_collabo_to_user_e75c53_idx",
            old_name="new_collabo_to_user_b5e8b5_idx",
        ),
        migrations.RenameIndex(
            model_name="newcollaborationinvite",
            new_name="new_collabo_status_4813d0_idx",
            old_name="new_collabo_status_c8b9c6_idx",
        ),
        migrations.RemoveField(
            model_name="project",
            name="collaborators",
        ),
        migrations.AddField(
            model_name="project",
            name="actual_hours",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="allow_file_sharing",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="enable_time_tracking",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="last_activity_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="progress_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="collaborationtask",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_collaboration_tasks",
                to="accounts.creatorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="collaborationtask",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_collaboration_tasks",
                to="accounts.creatorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_projects",
                to="accounts.creatorprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["status", "priority"], name="projects_status_b3b152_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["owner", "status"], name="projects_owner_i_597fe2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["last_activity_at"], name="projects_last_ac_c42588_idx"
            ),
        ),
        migrations.AddField(
            model_name="taskcomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_comments",
                to="accounts.creatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="taskcomment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="collaborations.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to="accounts.creatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tasks",
                to="accounts.creatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="depends_on",
            field=models.ManyToManyField(
                blank=True, related_name="blocking_tasks", to="collaborations.task"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="collaborations.project",
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_milestones",
                to="accounts.creatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="collaborations.project",
            ),
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_memberships",
                to="accounts.creatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="collaborations.project",
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="newer_versions",
                to="collaborations.projectfile",
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="collaborations.project",
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="collaborations.task",
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_files",
                to="accounts.creatorprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "status"], name="tasks_project_fe19a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assignee", "status"], name="tasks_assigne_972e70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["due_date"], name="tasks_due_dat_0359a9_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["board_order"], name="tasks_board_o_a10eca_idx"),
        ),
        migrations.AddIndex(
            model_name="projectmilestone",
            index=models.Index(
                fields=["project", "status"], name="project_mil_project_bc846a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmilestone",
            index=models.Index(
                fields=["due_date"], name="project_mil_due_dat_c8bee4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["project", "role"], name="project_mem_project_ce1662_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectmembership",
            unique_together={("project", "member")},
        ),
        migrations.AddIndex(
            model_name="projectfile",
            index=models.Index(
                fields=["project", "file_type"], name="project_fil_project_2531b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectfile",
            index=models.Index(
                fields=["uploaded_by", "created_at"],
                name="project_fil_uploade_46e320_idx",
            ),
        ),
    ]
