# Generated by Django 4.2.16 on 2025-09-25 21:50

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "auth_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CreatorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("visual_arts", "Visual Arts"),
                            ("performing_arts", "Performing Arts"),
                            ("literary_arts", "Literary Arts"),
                            ("design", "Design"),
                            ("digital_arts", "Digital Arts"),
                            ("crafts", "Crafts"),
                            ("media_arts", "Media Arts"),
                            ("culinary_arts", "Culinary Arts"),
                            ("architecture", "Architecture"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subcategory", models.CharField(blank=True, max_length=100)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("professional", "Professional"),
                        ],
                        max_length=15,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                ("spotify_url", models.URLField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("is_validated", models.BooleanField(default=False)),
                ("validation_score", models.FloatField(default=0.0)),
                ("health_score", models.FloatField(default=0.0)),
                ("activity_score", models.FloatField(default=0.0)),
                ("connection_score", models.FloatField(default=0.0)),
                ("feedback_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Creator Profile",
                "verbose_name_plural": "Creator Profiles",
                "db_table": "creator_profiles",
            },
        ),
        migrations.CreateModel(
            name="PremiumAddon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "addon_type",
                    models.CharField(
                        choices=[
                            ("storage", "Extra Storage"),
                            ("ai_credits", "AI Generation Credits"),
                            ("collaborations", "Extra Collaborations"),
                            ("analytics", "Advanced Analytics"),
                            ("priority_support", "Priority Support"),
                            ("custom_domain", "Custom Domain"),
                            ("white_label", "White Label Branding"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("storage_gb", models.IntegerField(default=0)),
                ("ai_credits", models.IntegerField(default=0)),
                ("collaboration_slots", models.IntegerField(default=0)),
                ("duration_days", models.IntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "premium_addons",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "price_monthly",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "price_yearly",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("max_portfolio_items", models.IntegerField(default=10)),
                ("max_collaborations", models.IntegerField(default=5)),
                ("ai_generations_per_month", models.IntegerField(default=10)),
                ("storage_gb", models.IntegerField(default=1)),
                ("priority_support", models.BooleanField(default=False)),
                ("advanced_analytics", models.BooleanField(default=False)),
                ("custom_branding", models.BooleanField(default=False)),
                ("api_access", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscription_plans",
                "ordering": ["price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("trial", "Trial"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "current_period_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("current_period_end", models.DateTimeField()),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("portfolio_items_used", models.IntegerField(default=0)),
                ("collaborations_used", models.IntegerField(default=0)),
                ("ai_generations_used", models.IntegerField(default=0)),
                ("storage_used_gb", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="UserAddon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "purchased_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField()),
                ("storage_used_gb", models.FloatField(default=0.0)),
                ("ai_credits_used", models.IntegerField(default=0)),
                ("collaborations_used", models.IntegerField(default=0)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "addon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.premiumaddon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_addons",
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed Amount"),
                            ("free_trial", "Free Trial Extension"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField()),
                ("max_uses", models.IntegerField(default=1)),
                ("current_uses", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicable_plans",
                    models.ManyToManyField(blank=True, to="accounts.subscriptionplan"),
                ),
            ],
            options={
                "db_table": "promo_codes",
            },
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=1000)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="portfolio/%Y/%m/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="thumbnails/%Y/%m/"
                    ),
                ),
                ("is_validated", models.BooleanField(default=False)),
                ("validation_score", models.FloatField(default=0.0)),
                ("is_original", models.BooleanField(default=True)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_items",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Item",
                "verbose_name_plural": "Portfolio Items",
                "db_table": "portfolio_items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription"),
                            ("addon", "Add-on"),
                            ("one_time", "One-time Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "addon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.useraddon",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.usersubscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=8, unique=True)),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("profile_verification", "Profile Verification"),
                            ("portfolio_approval", "Portfolio Approval"),
                            (
                                "collaboration_verification",
                                "Collaboration Verification",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("used", "Used"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_codes",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "approval_codes",
            },
        ),
        migrations.CreateModel(
            name="UsageLimit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("portfolio_items", "Portfolio Items"),
                            ("collaborations", "Collaborations"),
                            ("ai_generations", "AI Generations"),
                            ("storage", "Storage"),
                            ("api_calls", "API Calls"),
                        ],
                        max_length=30,
                    ),
                ),
                ("limit_value", models.IntegerField()),
                ("current_usage", models.IntegerField(default=0)),
                ("reset_period", models.CharField(default="monthly", max_length=20)),
                ("last_reset", models.DateTimeField(default=django.utils.timezone.now)),
                ("next_reset", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_limits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "usage_limits",
                "unique_together": {("user", "feature_type")},
            },
        ),
        migrations.CreateModel(
            name="PromoCodeUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "discount_applied",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("used_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.paymenthistory",
                    ),
                ),
                (
                    "promo_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="accounts.promocode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "promo_code_usage",
                "unique_together": {("promo_code", "user")},
            },
        ),
        migrations.CreateModel(
            name="ProfileFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("constructive", "Constructive"),
                            ("report", "Report"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_received",
                        to="accounts.creatorprofile",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_given",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Feedback",
                "verbose_name_plural": "Profile Feedback",
                "db_table": "profile_feedback",
                "unique_together": {("profile", "reviewer")},
            },
        ),
        migrations.AddIndex(
            model_name="creatorprofile",
            index=models.Index(
                fields=["category", "experience_level"],
                name="creator_pro_categor_76690f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="creatorprofile",
            index=models.Index(
                fields=["location"], name="creator_pro_locatio_c0ed29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creatorprofile",
            index=models.Index(
                fields=["health_score"], name="creator_pro_health__f4f13e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalcode",
            index=models.Index(
                fields=["code", "status"], name="approval_co_code_53bfb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalcode",
            index=models.Index(
                fields=["profile", "code_type"], name="approval_co_profile_ed2216_idx"
            ),
        ),
    ]
