# Generated by Django 4.2.16 on 2025-08-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_personalityquiz_personalityprofile_and_more"),
    ]

    operations = []
