# Generated by Django 4.2.16 on 2025-08-16 20:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20250816_2041"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=8, unique=True)),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("profile_verification", "Profile Verification"),
                            ("portfolio_approval", "Portfolio Approval"),
                            (
                                "collaboration_verification",
                                "Collaboration Verification",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("used", "Used"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_codes",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "approval_codes",
                "indexes": [
                    models.Index(
                        fields=["code", "status"], name="approval_co_code_53bfb9_idx"
                    ),
                    models.Index(
                        fields=["profile", "code_type"],
                        name="approval_co_profile_ed2216_idx",
                    ),
                ],
            },
        ),
    ]
