# Generated by Django 4.2.16 on 2025-08-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_approvalcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalityprofile",
            name="profile",
        ),
        migrations.AlterUniqueTogether(
            name="personalityresponse",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="personalityresponse",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="personalityresponse",
            name="quiz",
        ),
        migrations.DeleteModel(
            name="CollaborationMatch",
        ),
        migrations.DeleteModel(
            name="PersonalityProfile",
        ),
        migrations.DeleteModel(
            name="PersonalityQuiz",
        ),
        migrations.DeleteModel(
            name="PersonalityResponse",
        ),
    ]
