# Generated by Django 4.2.16 on 2025-08-19 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("user_signed_in", "User Signed In"),
                            ("profile_updated", "Profile Updated"),
                            ("message_received", "Message Received"),
                            ("profile_followed", "Profile Followed"),
                            ("collaboration_invite", "Collaboration Invite"),
                            ("system_announcement", "System Announcement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "read_at"],
                        name="notificatio_user_id_6c7360_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_611c58_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityFeed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("profile_created", "Profile Created"),
                            ("profile_updated", "Profile Updated"),
                            ("message_sent", "Message Sent"),
                            ("collaboration_joined", "Collaboration Joined"),
                            ("content_generated", "Content Generated"),
                            ("profile_followed", "Profile Followed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=50, null=True)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actor_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_feed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity_feed",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="activity_fe_user_id_c6989a_idx",
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="activity_fe_actor_i_5bc14b_idx",
                    ),
                ],
            },
        ),
    ]
