# Generated by Django 4.2.16 on 2025-09-25 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("websocket_connected", models.BooleanField(default=False)),
                ("connection_count", models.PositiveIntegerField(default=0)),
                ("last_connected_at", models.DateTimeField(auto_now=True)),
                (
                    "preferences",
                    models.JSONField(
                        default=dict, help_text="User notification preferences"
                    ),
                ),
                (
                    "push_subscription",
                    models.JSONField(
                        blank=True, help_text="Web push subscription data", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_subscriptions",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="notificatio_user_id_62d5ea_idx",
                    ),
                    models.Index(
                        fields=["websocket_connected"],
                        name="notificatio_websock_4bc63d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("user_signed_in", "User Signed In"),
                            ("profile_updated", "Profile Updated"),
                            ("message_received", "Message Received"),
                            ("profile_followed", "Profile Followed"),
                            ("collaboration_invite", "Collaboration Invite"),
                            ("system_announcement", "System Announcement"),
                            ("match_found", "New Match Found"),
                            ("match_accepted", "Match Accepted"),
                            ("match_declined", "Match Declined"),
                            ("match_feedback_received", "Match Feedback Received"),
                            ("match_expired", "Match Expired"),
                            (
                                "matching_preferences_updated",
                                "Matching Preferences Updated",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "read_at"],
                        name="notificatio_user_id_6c7360_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_611c58_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_match", "New Match Found"),
                            ("match_viewed", "Match Viewed"),
                            ("match_accepted", "Match Accepted"),
                            ("match_declined", "Match Declined"),
                            ("feedback_received", "Feedback Received"),
                            ("match_expired", "Match Expired"),
                            ("rematch_suggested", "Rematch Suggested"),
                        ],
                        max_length=30,
                    ),
                ),
                ("match_id", models.UUIDField(help_text="ID of the related match")),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional notification data"
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_match_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "match_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="match_notif_recipie_9f8d9c_idx",
                    ),
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="match_notif_recipie_4b8d77_idx",
                    ),
                    models.Index(
                        fields=["match_id"], name="match_notif_match_i_6a7b0b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityFeed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("profile_created", "Profile Created"),
                            ("profile_updated", "Profile Updated"),
                            ("message_sent", "Message Sent"),
                            ("collaboration_joined", "Collaboration Joined"),
                            ("content_generated", "Content Generated"),
                            ("profile_followed", "Profile Followed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=50, null=True)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actor_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_feed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity_feed",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="activity_fe_user_id_c6989a_idx",
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="activity_fe_actor_i_5bc14b_idx",
                    ),
                ],
            },
        ),
    ]
