# Generated by Django 4.2.16 on 2025-09-25 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("host", "Host"),
                            ("co_host", "Co-Host"),
                            ("participant", "Participant"),
                            ("observer", "Observer"),
                        ],
                        default="participant",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("joined", "Joined"),
                            ("left", "Left"),
                            ("kicked", "Kicked"),
                        ],
                        default="invited",
                        max_length=20,
                    ),
                ),
                ("can_share_screen", models.BooleanField(default=True)),
                ("can_record", models.BooleanField(default=False)),
                ("can_mute_others", models.BooleanField(default=False)),
                ("can_manage_participants", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("connection_quality", models.CharField(blank=True, max_length=20)),
                ("peer_id", models.CharField(blank=True, max_length=100)),
                ("ice_servers", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "room_participants",
            },
        ),
        migrations.CreateModel(
            name="VideoRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("collaboration", "Collaboration Session"),
                            ("interview", "Interview"),
                            ("presentation", "Presentation"),
                            ("brainstorming", "Brainstorming"),
                            ("review", "Review Session"),
                        ],
                        default="collaboration",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("max_participants", models.IntegerField(default=10)),
                ("is_recording_enabled", models.BooleanField(default=True)),
                ("is_screen_sharing_enabled", models.BooleanField(default=True)),
                ("is_chat_enabled", models.BooleanField(default=True)),
                ("is_whiteboard_enabled", models.BooleanField(default=True)),
                ("require_approval", models.BooleanField(default=False)),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end", models.DateTimeField(blank=True, null=True)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("signaling_server", models.CharField(blank=True, max_length=200)),
                ("room_token", models.CharField(blank=True, max_length=100)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="joined_rooms",
                        through="video_collaboration.RoomParticipant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "video_rooms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Whiteboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Collaboration Whiteboard", max_length=200
                    ),
                ),
                ("canvas_data", models.JSONField(blank=True, default=dict)),
                ("canvas_width", models.IntegerField(default=1920)),
                ("canvas_height", models.IntegerField(default=1080)),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("export_url", models.URLField(blank=True)),
                ("export_format", models.CharField(blank=True, max_length=10)),
                (
                    "allowed_editors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="editable_whiteboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiteboard",
                        to="video_collaboration.videoroom",
                    ),
                ),
            ],
            options={
                "db_table": "whiteboards",
            },
        ),
        migrations.CreateModel(
            name="VideoRecording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recording", "Recording"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="recording",
                        max_length=20,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("720p", "720p HD"),
                            ("1080p", "1080p Full HD"),
                            ("480p", "480p SD"),
                        ],
                        default="720p",
                        max_length=10,
                    ),
                ),
                ("duration_seconds", models.IntegerField(default=0)),
                ("file_size_mb", models.FloatField(default=0)),
                ("video_file_url", models.URLField(blank=True)),
                ("audio_file_url", models.URLField(blank=True)),
                ("transcript_file_url", models.URLField(blank=True)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("processing_error", models.TextField(blank=True)),
                (
                    "allowed_viewers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="accessible_recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="video_collaboration.videoroom",
                    ),
                ),
            ],
            options={
                "db_table": "video_recordings",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Message"),
                            ("file", "File Share"),
                            ("link", "Link Share"),
                            ("system", "System Message"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("file_url", models.URLField(blank=True)),
                ("file_name", models.CharField(blank=True, max_length=200)),
                ("file_size", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_private", models.BooleanField(default=False)),
                ("reactions", models.JSONField(blank=True, default=dict)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="private_video_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="video_collaboration.videoroom",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "video_messages",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ScreenShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("ended", "Ended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("screen_type", models.CharField(blank=True, max_length=50)),
                ("resolution", models.CharField(blank=True, max_length=20)),
                ("frame_rate", models.IntegerField(default=30)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("is_recorded", models.BooleanField(default=False)),
                ("recording_url", models.URLField(blank=True)),
                (
                    "presenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screen_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screen_shares",
                        to="video_collaboration.videoroom",
                    ),
                ),
            ],
            options={
                "db_table": "screen_shares",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="roomparticipant",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="video_collaboration.videoroom",
            ),
        ),
        migrations.AddField(
            model_name="roomparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="ConnectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("join", "User Joined"),
                            ("leave", "User Left"),
                            ("connection_failed", "Connection Failed"),
                            ("reconnect", "Reconnection"),
                            ("quality_change", "Quality Change"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("connection_quality", models.CharField(blank=True, max_length=20)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("bandwidth_kbps", models.IntegerField(blank=True, null=True)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_logs",
                        to="video_collaboration.videoroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_connection_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "video_connection_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="roomparticipant",
            unique_together={("room", "user")},
        ),
    ]
