# Generated by Django 4.2.16 on 2025-08-16 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("accounts", "0001_initial"),
        ("collaborations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="collaboration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="collaborations.collaboration",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_rooms",
                to="accounts.creatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="participants",
            field=models.ManyToManyField(
                related_name="chat_rooms", to="accounts.creatorprofile"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chatroom",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="accounts.creatorprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="messagereadstatus",
            index=models.Index(
                fields=["reader", "read_at"], name="message_rea_reader__80e1ba_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagereadstatus",
            unique_together={("message", "reader")},
        ),
        migrations.AlterUniqueTogether(
            name="meetingresponse",
            unique_together={("meeting", "participant")},
        ),
        migrations.AddIndex(
            model_name="meetinginvite",
            index=models.Index(
                fields=["scheduled_at", "status"], name="meeting_inv_schedul_36ba81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetinginvite",
            index=models.Index(
                fields=["organizer", "status"], name="meeting_inv_organiz_7a984e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["room_type", "is_active"], name="chat_rooms_room_ty_a475b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["last_message_at"], name="chat_rooms_last_me_a06a9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["room", "created_at"], name="chat_messag_room_id_cc7f0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender", "created_at"], name="chat_messag_sender__7a605a_idx"
            ),
        ),
    ]
