# Generated by Django 4.2.16 on 2025-10-06 03:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("pro", "Pro"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("price_monthly", models.DecimalField(decimal_places=2, max_digits=8)),
                ("price_yearly", models.DecimalField(decimal_places=2, max_digits=8)),
                ("profile_views_limit", models.IntegerField(default=10)),
                ("collaboration_invites_limit", models.IntegerField(default=3)),
                ("ai_suggestions_limit", models.IntegerField(default=5)),
                ("portfolio_items_limit", models.IntegerField(default=5)),
                ("can_send_invites_only", models.BooleanField(default=False)),
                ("has_visibility_controls", models.BooleanField(default=False)),
                ("has_auto_translation", models.BooleanField(default=False)),
                ("has_ai_portfolio_generator", models.BooleanField(default=False)),
                ("has_priority_support", models.BooleanField(default=False)),
                ("has_analytics", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "subscription_tiers",
                "ordering": ["price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription Payment"),
                            ("portfolio_generator", "AI Portfolio Generator"),
                            ("premium_feature", "Premium Feature"),
                            ("refund", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.CharField(max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "payment_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=500)),
                (
                    "ad_type",
                    models.CharField(
                        choices=[
                            ("banner", "Banner"),
                            ("sidebar", "Sidebar"),
                            ("interstitial", "Interstitial"),
                            ("native", "Native"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("courses", "Online Courses"),
                            ("equipment", "Equipment & Tools"),
                            ("software", "Software & Apps"),
                            ("services", "Creative Services"),
                            ("events", "Events & Workshops"),
                        ],
                        max_length=15,
                    ),
                ),
                ("target_categories", models.JSONField(default=list)),
                ("target_experience_levels", models.JSONField(default=list)),
                ("target_locations", models.JSONField(default=list)),
                ("image_url", models.URLField()),
                ("click_url", models.URLField()),
                (
                    "call_to_action",
                    models.CharField(default="Learn More", max_length=50),
                ),
                ("advertiser_name", models.CharField(max_length=100)),
                ("budget_daily", models.DecimalField(decimal_places=2, max_digits=8)),
                ("cost_per_click", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("conversions", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "advertisements",
                "indexes": [
                    models.Index(
                        fields=["is_active", "start_date", "end_date"],
                        name="advertiseme_is_acti_06fe9c_idx",
                    ),
                    models.Index(
                        fields=["category"], name="advertiseme_categor_00403b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                ("next_billing_date", models.DateTimeField()),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "last_payment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("profile_views_used", models.IntegerField(default=0)),
                ("invites_sent_count", models.IntegerField(default=0)),
                ("ai_suggestions_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "active_subscriptions",
                "indexes": [
                    models.Index(
                        fields=["status", "next_billing_date"],
                        name="active_subs_status_762e40_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AdImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("was_clicked", models.BooleanField(default=False)),
                ("impression_time", models.DateTimeField(auto_now_add=True)),
                ("click_time", models.DateTimeField(blank=True, null=True)),
                ("page_context", models.CharField(max_length=50)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impression_records",
                        to="subscriptions.advertisement",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_impressions",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ad_impressions",
                "unique_together": {("ad", "profile", "impression_time")},
            },
        ),
    ]
