# Generated by Django 4.2.16 on 2025-09-25 20:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
                ("decimal_places", models.IntegerField(default=2)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "exchange_rate_to_usd",
                    models.DecimalField(decimal_places=6, default=1.0, max_digits=10),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "globalization_currency",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("zh", "Chinese (Simplified)"),
                            ("zh-tw", "Chinese (Traditional)"),
                            ("ja", "Japanese"),
                            ("ko", "Korean"),
                            ("pt", "Portuguese"),
                            ("it", "Italian"),
                            ("ru", "Russian"),
                            ("ar", "Arabic"),
                            ("he", "Hebrew"),
                            ("hi", "Hindi"),
                            ("th", "Thai"),
                        ],
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("native_name", models.CharField(max_length=100)),
                ("is_rtl", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "completion_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
            ],
            options={
                "db_table": "globalization_language",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "region_type",
                    models.CharField(
                        choices=[
                            ("NA", "North America"),
                            ("SA", "South America"),
                            ("EU", "Europe"),
                            ("AS", "Asia"),
                            ("AF", "Africa"),
                            ("OC", "Oceania"),
                            ("ME", "Middle East"),
                        ],
                        max_length=2,
                    ),
                ),
                ("timezone_offset", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("data_residency_required", models.BooleanField(default=False)),
                ("gdpr_applicable", models.BooleanField(default=False)),
                ("ccpa_applicable", models.BooleanField(default=False)),
                (
                    "default_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_regions",
                        to="globalization.currency",
                    ),
                ),
                (
                    "default_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_regions",
                        to="globalization.language",
                    ),
                ),
            ],
            options={
                "db_table": "globalization_region",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TranslationKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("ui", "User Interface"),
                            ("email", "Email Templates"),
                            ("notification", "Notifications"),
                            ("error", "Error Messages"),
                            ("help", "Help Text"),
                            ("marketing", "Marketing Content"),
                            ("legal", "Legal Documents"),
                        ],
                        default="ui",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "globalization_translation_key",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="UserLocalization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("date_format", models.CharField(default="YYYY-MM-DD", max_length=20)),
                ("time_format", models.CharField(default="24h", max_length=20)),
                ("number_format", models.CharField(default="1,234.56", max_length=20)),
                ("auto_translate", models.BooleanField(default=True)),
                ("show_original_text", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        default="USD",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalization.currency",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        default="en",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalization.language",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalization.region",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localization",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "globalization_user_localization",
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="globalization.translationkey",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="globalization.language",
                    ),
                ),
                (
                    "translator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "globalization_translation",
                "ordering": ["key__key", "language__code"],
                "unique_together": {("key", "language")},
            },
        ),
        migrations.CreateModel(
            name="LocalizedContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("project_description", "Project Description"),
                            ("skill_name", "Skill Name"),
                            ("category_name", "Category Name"),
                            ("notification_template", "Notification Template"),
                            ("email_template", "Email Template"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content_id", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_machine_translated", models.BooleanField(default=False)),
                ("is_human_reviewed", models.BooleanField(default=False)),
                (
                    "quality_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalization.language",
                    ),
                ),
            ],
            options={
                "db_table": "globalization_localized_content",
                "ordering": ["content_type", "content_id", "language__code"],
                "unique_together": {("content_type", "content_id", "language")},
            },
        ),
        migrations.CreateModel(
            name="LocalizationAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("active_users", models.IntegerField(default=0)),
                ("page_views", models.IntegerField(default=0)),
                ("translation_requests", models.IntegerField(default=0)),
                ("auto_translations", models.IntegerField(default=0)),
                ("human_translations", models.IntegerField(default=0)),
                (
                    "translation_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "user_satisfaction",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalization.language",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="globalization.region",
                    ),
                ),
            ],
            options={
                "db_table": "globalization_localization_analytics",
                "ordering": ["-date", "language__code"],
                "unique_together": {("date", "language", "region")},
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=6, max_digits=10)),
                ("date", models.DateField()),
                ("source", models.CharField(default="api", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_rates_from",
                        to="globalization.currency",
                    ),
                ),
                (
                    "to_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_rates_to",
                        to="globalization.currency",
                    ),
                ),
            ],
            options={
                "db_table": "globalization_exchange_rate",
                "ordering": ["-date", "from_currency", "to_currency"],
                "unique_together": {("from_currency", "to_currency", "date")},
            },
        ),
    ]
