# Generated by Django 4.2.16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_login', 'User Login'), ('user_logout', 'User Logout'), ('page_view', 'Page View'), ('match_request', 'Match Request'), ('match_acceptance', 'Match Acceptance'), ('collaboration_invite', 'Collaboration Invite'), ('message_sent', 'Message Sent'), ('notification_sent', 'Notification Sent'), ('notification_opened', 'Notification Opened'), ('api_request', 'API Request'), ('error_occurred', 'Error Occurred')], max_length=50)),
                ('event_data', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_match_requests', models.IntegerField(default=0)),
                ('successful_matches', models.IntegerField(default=0)),
                ('match_acceptance_rate', models.FloatField(default=0.0)),
                ('avg_match_score', models.FloatField(default=0.0)),
                ('avg_matching_time', models.FloatField(default=0.0)),
                ('cache_hit_rate', models.FloatField(default=0.0)),
                ('user_feedback_positive', models.IntegerField(default=0)),
                ('user_feedback_negative', models.IntegerField(default=0)),
                ('matches_leading_to_collaboration', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_notifications_sent', models.IntegerField(default=0)),
                ('push_notifications_sent', models.IntegerField(default=0)),
                ('email_notifications_sent', models.IntegerField(default=0)),
                ('notifications_opened', models.IntegerField(default=0)),
                ('notifications_clicked', models.IntegerField(default=0)),
                ('open_rate', models.FloatField(default=0.0)),
                ('click_rate', models.FloatField(default=0.0)),
                ('avg_delivery_time', models.FloatField(default=0.0)),
                ('delivery_failure_rate', models.FloatField(default=0.0)),
                ('users_opted_out', models.IntegerField(default=0)),
                ('users_opted_in', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users_daily', models.IntegerField(default=0)),
                ('active_users_weekly', models.IntegerField(default=0)),
                ('active_users_monthly', models.IntegerField(default=0)),
                ('new_registrations', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('avg_session_duration', models.DurationField(default=django.utils.timezone.timedelta)),
                ('total_page_views', models.IntegerField(default=0)),
                ('total_matches_generated', models.IntegerField(default=0)),
                ('successful_matches', models.IntegerField(default=0)),
                ('collaboration_invites_sent', models.IntegerField(default=0)),
                ('collaboration_invites_accepted', models.IntegerField(default=0)),
                ('messages_exchanged', models.IntegerField(default=0)),
                ('avg_api_response_time', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('cache_hit_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealtimeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_realtime_sessions', models.IntegerField(default=0)),
                ('avg_session_duration', models.DurationField(default=django.utils.timezone.timedelta)),
                ('concurrent_users_peak', models.IntegerField(default=0)),
                ('total_messages_sent', models.IntegerField(default=0)),
                ('avg_messages_per_session', models.FloatField(default=0.0)),
                ('translation_requests', models.IntegerField(default=0)),
                ('avg_message_latency', models.FloatField(default=0.0)),
                ('connection_success_rate', models.FloatField(default=0.0)),
                ('websocket_errors', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEngagementMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sessions_count', models.IntegerField(default=0)),
                ('total_session_duration', models.DurationField(default=django.utils.timezone.timedelta)),
                ('avg_session_duration', models.DurationField(default=django.utils.timezone.timedelta)),
                ('pages_viewed', models.IntegerField(default=0)),
                ('actions_performed', models.IntegerField(default=0)),
                ('notifications_clicked', models.IntegerField(default=0)),
                ('matches_viewed', models.IntegerField(default=0)),
                ('collaborations_initiated', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='userengagementmetric',
            index=models.Index(fields=['date', 'user'], name='analytics_u_date_b0f2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagementmetric',
            index=models.Index(fields=['created_at'], name='analytics_u_created_c7e4b1_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimeanalytics',
            index=models.Index(fields=['date'], name='analytics_r_date_8a7c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimeanalytics',
            index=models.Index(fields=['concurrent_users_peak'], name='analytics_r_concurr_0b5e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='platformmetric',
            index=models.Index(fields=['date'], name='analytics_p_date_f3b8e1_idx'),
        ),
        migrations.AddIndex(
            model_name='platformmetric',
            index=models.Index(fields=['created_at'], name='analytics_p_created_a9d6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationanalytics',
            index=models.Index(fields=['date'], name='analytics_n_date_7e4f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationanalytics',
            index=models.Index(fields=['open_rate', 'click_rate'], name='analytics_n_open_ra_5c8d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='matchinganalytics',
            index=models.Index(fields=['date'], name='analytics_m_date_2f6e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='matchinganalytics',
            index=models.Index(fields=['match_acceptance_rate'], name='analytics_m_match_a_4b9e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='analytics_a_event_t_8c5f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_a_user_id_7d4e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['timestamp'], name='analytics_a_timesta_9b6f1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userengagementmetric',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='realtimeanalytics',
            unique_together={('date',)},
        ),
        migrations.AlterUniqueTogether(
            name='platformmetric',
            unique_together={('date',)},
        ),
        migrations.AlterUniqueTogether(
            name='notificationanalytics',
            unique_together={('date',)},
        ),
        migrations.AlterUniqueTogether(
            name='matchinganalytics',
            unique_together={('date',)},
        ),
    ]
