# Generated by Django 4.2.16 on 2025-09-25 21:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RealtimeAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("total_realtime_sessions", models.IntegerField(default=0)),
                (
                    "avg_session_duration",
                    models.DurationField(default=datetime.timedelta),
                ),
                ("concurrent_users_peak", models.IntegerField(default=0)),
                ("total_messages_sent", models.IntegerField(default=0)),
                ("avg_messages_per_session", models.FloatField(default=0.0)),
                ("translation_requests", models.IntegerField(default=0)),
                ("avg_message_latency", models.FloatField(default=0.0)),
                ("connection_success_rate", models.FloatField(default=0.0)),
                ("websocket_errors", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="analytics_r_date_940ac0_idx"),
                    models.Index(
                        fields=["concurrent_users_peak"],
                        name="analytics_r_concurr_a3778a_idx",
                    ),
                ],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="PlatformMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("total_users", models.IntegerField(default=0)),
                ("active_users_daily", models.IntegerField(default=0)),
                ("active_users_weekly", models.IntegerField(default=0)),
                ("active_users_monthly", models.IntegerField(default=0)),
                ("new_registrations", models.IntegerField(default=0)),
                ("total_sessions", models.IntegerField(default=0)),
                (
                    "avg_session_duration",
                    models.DurationField(default=datetime.timedelta),
                ),
                ("total_page_views", models.IntegerField(default=0)),
                ("total_matches_generated", models.IntegerField(default=0)),
                ("successful_matches", models.IntegerField(default=0)),
                ("collaboration_invites_sent", models.IntegerField(default=0)),
                ("collaboration_invites_accepted", models.IntegerField(default=0)),
                ("messages_exchanged", models.IntegerField(default=0)),
                ("avg_api_response_time", models.FloatField(default=0.0)),
                ("error_rate", models.FloatField(default=0.0)),
                ("cache_hit_rate", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="analytics_p_date_23fc9a_idx"),
                    models.Index(
                        fields=["created_at"], name="analytics_p_created_7ccf52_idx"
                    ),
                ],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="NotificationAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("total_notifications_sent", models.IntegerField(default=0)),
                ("push_notifications_sent", models.IntegerField(default=0)),
                ("email_notifications_sent", models.IntegerField(default=0)),
                ("notifications_opened", models.IntegerField(default=0)),
                ("notifications_clicked", models.IntegerField(default=0)),
                ("open_rate", models.FloatField(default=0.0)),
                ("click_rate", models.FloatField(default=0.0)),
                ("avg_delivery_time", models.FloatField(default=0.0)),
                ("delivery_failure_rate", models.FloatField(default=0.0)),
                ("users_opted_out", models.IntegerField(default=0)),
                ("users_opted_in", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="analytics_n_date_7b455d_idx"),
                    models.Index(
                        fields=["open_rate", "click_rate"],
                        name="analytics_n_open_ra_a4e67f_idx",
                    ),
                ],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="MatchingAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("total_match_requests", models.IntegerField(default=0)),
                ("successful_matches", models.IntegerField(default=0)),
                ("match_acceptance_rate", models.FloatField(default=0.0)),
                ("avg_match_score", models.FloatField(default=0.0)),
                ("avg_matching_time", models.FloatField(default=0.0)),
                ("cache_hit_rate", models.FloatField(default=0.0)),
                ("user_feedback_positive", models.IntegerField(default=0)),
                ("user_feedback_negative", models.IntegerField(default=0)),
                ("matches_leading_to_collaboration", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="analytics_m_date_0a0c3d_idx"),
                    models.Index(
                        fields=["match_acceptance_rate"],
                        name="analytics_m_match_a_a3bb8b_idx",
                    ),
                ],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="UserEngagementMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("sessions_count", models.IntegerField(default=0)),
                (
                    "total_session_duration",
                    models.DurationField(default=datetime.timedelta),
                ),
                (
                    "avg_session_duration",
                    models.DurationField(default=datetime.timedelta),
                ),
                ("pages_viewed", models.IntegerField(default=0)),
                ("actions_performed", models.IntegerField(default=0)),
                ("notifications_clicked", models.IntegerField(default=0)),
                ("matches_viewed", models.IntegerField(default=0)),
                ("collaborations_initiated", models.IntegerField(default=0)),
                ("messages_sent", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "user"], name="analytics_u_date_793fd0_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_u_created_b9c18a_idx"
                    ),
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("user_login", "User Login"),
                            ("user_logout", "User Logout"),
                            ("page_view", "Page View"),
                            ("match_request", "Match Request"),
                            ("match_acceptance", "Match Acceptance"),
                            ("collaboration_invite", "Collaboration Invite"),
                            ("message_sent", "Message Sent"),
                            ("notification_sent", "Notification Sent"),
                            ("notification_opened", "Notification Opened"),
                            ("api_request", "API Request"),
                            ("error_occurred", "Error Occurred"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_data", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="analytics_a_event_t_64745b_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="analytics_a_user_id_5c8c13_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="analytics_a_timesta_aef2a5_idx"
                    ),
                ],
            },
        ),
    ]
