# Generated by Django 4.2.16 on 2025-08-16 20:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentValidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("profile", "Profile"),
                            ("portfolio", "Portfolio Item"),
                            ("message", "Chat Message"),
                            ("collaboration", "Collaboration"),
                        ],
                        max_length=15,
                    ),
                ),
                ("content_id", models.CharField(max_length=100)),
                ("validation_score", models.FloatField()),
                ("is_valid", models.BooleanField(default=True)),
                ("feedback", models.TextField(blank=True, max_length=1000)),
                ("model_version", models.CharField(default="v1.0", max_length=50)),
                ("validation_type", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "content_validations",
                "indexes": [
                    models.Index(
                        fields=["content_type", "content_id"],
                        name="content_val_content_dc07f9_idx",
                    ),
                    models.Index(
                        fields=["validation_score"],
                        name="content_val_validat_a48bec_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIGeneratedContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("bio", "Profile Bio"),
                            ("description", "Project Description"),
                            ("caption", "Social Media Caption"),
                            ("script", "Video Script"),
                            ("lyrics", "Song Lyrics"),
                        ],
                        max_length=15,
                    ),
                ),
                ("prompt", models.TextField(max_length=1000)),
                ("generated_content", models.TextField(max_length=5000)),
                ("quality_score", models.FloatField(default=0.0)),
                ("is_approved", models.BooleanField(default=False)),
                ("model_used", models.CharField(default="gpt-4", max_length=100)),
                ("generation_time", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_content",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ai_generated_content",
                "indexes": [
                    models.Index(
                        fields=["creator", "content_type"],
                        name="ai_generate_creator_5f6057_idx",
                    ),
                    models.Index(
                        fields=["quality_score"], name="ai_generate_quality_fe30a6_idx"
                    ),
                ],
            },
        ),
    ]
