# Generated by Django 4.2.16 on 2025-09-25 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentGenerationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("social_media_post", "Social Media Post"),
                            ("video_script", "Video Script"),
                            ("blog_post", "Blog Post"),
                            ("marketing_copy", "Marketing Copy"),
                            ("creative_writing", "Creative Writing"),
                            ("product_description", "Product Description"),
                            ("email_campaign", "Email Campaign"),
                            ("press_release", "Press Release"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("twitter", "Twitter"),
                            ("linkedin", "LinkedIn"),
                            ("facebook", "Facebook"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField(max_length=2000)),
                ("topic", models.CharField(max_length=200)),
                ("target_audience", models.CharField(blank=True, max_length=200)),
                ("tone", models.CharField(blank=True, max_length=50)),
                ("word_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.PositiveIntegerField(default=1000)),
                ("custom_parameters", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                (
                    "cost_estimate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_requests",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "content_generation_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(help_text="Cosine similarity score (0-1)"),
                ),
                (
                    "compatibility_score",
                    models.FloatField(help_text="Overall compatibility score (0-100)"),
                ),
                (
                    "match_reasons",
                    models.JSONField(
                        default=list, help_text="List of reasons for the match"
                    ),
                ),
                (
                    "shared_skills",
                    models.JSONField(default=list, help_text="Skills in common"),
                ),
                (
                    "complementary_skills",
                    models.JSONField(default=list, help_text="Complementary skills"),
                ),
                (
                    "match_type",
                    models.CharField(
                        default="general",
                        help_text="Type of match (collaboration, mentorship, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "match_filters",
                    models.JSONField(
                        default=dict, help_text="Filters used for matching"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("viewed", "Viewed"),
                            ("interested", "Interested"),
                            ("contacted", "Contacted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "matched_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_matches",
                        to="accounts.creatorprofile",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_requests",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "match_results",
                "ordering": ["-compatibility_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("find_matches", "Find Matches"),
                            ("batch_match", "Batch Match"),
                            ("similar_creators", "Similar Creators"),
                            ("collaboration_match", "Collaboration Match"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "filters_used",
                    models.JSONField(
                        default=dict, help_text="Filters applied to the search"
                    ),
                ),
                ("results_count", models.PositiveIntegerField(default=0)),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(
                        help_text="Processing time in milliseconds"
                    ),
                ),
                ("embedding_version", models.CharField(default="v1.0", max_length=50)),
                ("top_similarity_score", models.FloatField(blank=True, null=True)),
                ("average_compatibility", models.FloatField(blank=True, null=True)),
                ("matches_viewed", models.PositiveIntegerField(default=0)),
                ("matches_contacted", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_history",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "match_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("quality", "Match Quality"),
                            ("relevance", "Relevance"),
                            ("accuracy", "Accuracy"),
                            ("usefulness", "Usefulness"),
                        ],
                        default="quality",
                        max_length=20,
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Optional feedback comment"),
                ),
                ("contacted_match", models.BooleanField(default=False)),
                ("collaboration_started", models.BooleanField(default=False)),
                ("would_recommend", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="ai_services.matchresult",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "match_feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("title", models.CharField(blank=True, max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("quality_score", models.FloatField(default=0.0)),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ],
                        null=True,
                    ),
                ),
                ("user_feedback", models.TextField(blank=True, max_length=1000)),
                ("is_published", models.BooleanField(default=False)),
                ("is_favorite", models.BooleanField(default=False)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_versions",
                        to="ai_services.generatedcontent",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_content",
                        to="ai_services.contentgenerationrequest",
                    ),
                ),
            ],
            options={
                "db_table": "generated_content",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreatorEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "embedding_vector",
                    models.JSONField(
                        help_text="Vector representation of creator profile"
                    ),
                ),
                ("embedding_version", models.CharField(default="v1.0", max_length=50)),
                (
                    "skills_hash",
                    models.CharField(
                        help_text="Hash of skills data used", max_length=64
                    ),
                ),
                (
                    "bio_hash",
                    models.CharField(help_text="Hash of bio data used", max_length=64),
                ),
                (
                    "interests_hash",
                    models.CharField(
                        help_text="Hash of interests data used", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_profile_update", models.DateTimeField(blank=True, null=True)),
                (
                    "creator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "creator_embeddings",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentValidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_valid", models.BooleanField(default=True)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("validation_data", models.JSONField(default=dict)),
                ("issues", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("flagged", "Flagged for Review"),
                            ("pending", "Pending Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("validated_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "portfolio_item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="accounts.portfolioitem",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "content_validations",
                "ordering": ["-validated_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=500)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("prompt", "Prompt Template"),
                            ("structure", "Content Structure"),
                            ("style", "Style Guide"),
                            ("format", "Format Template"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("social_media_post", "Social Media Post"),
                            ("video_script", "Video Script"),
                            ("blog_post", "Blog Post"),
                            ("marketing_copy", "Marketing Copy"),
                            ("creative_writing", "Creative Writing"),
                            ("product_description", "Product Description"),
                            ("email_campaign", "Email Campaign"),
                            ("press_release", "Press Release"),
                        ],
                        max_length=30,
                    ),
                ),
                ("prompt_template", models.TextField()),
                ("default_parameters", models.JSONField(blank=True, default=dict)),
                ("example_output", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_templates",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "content_templates",
                "ordering": ["-usage_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, max_length=300)),
                ("color", models.CharField(default="#007bff", max_length=7)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="ai_services.contentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Content Categories",
                "db_table": "content_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AIContentGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "generation_type",
                    models.CharField(
                        choices=[
                            ("music", "Music Generation"),
                            ("lyrics", "Lyrics Generation"),
                            ("artwork", "Artwork Generation"),
                            ("story", "Story Generation"),
                            ("concept", "Concept Development"),
                            ("bio", "Profile Bio"),
                            ("description", "Project Description"),
                            ("caption", "Social Media Caption"),
                            ("script", "Video Script"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField(max_length=2000)),
                ("parameters", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("generated_content", models.TextField(blank=True)),
                ("quality_score", models.FloatField(default=0.0)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_generations",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ai_content_generations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserUsageTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("content_generation", "Content Generation"),
                            ("template_usage", "Template Usage"),
                            ("api_call", "API Call"),
                        ],
                        max_length=30,
                    ),
                ),
                ("tokens_consumed", models.PositiveIntegerField(default=0)),
                (
                    "cost_incurred",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("daily_count", models.PositiveIntegerField(default=0)),
                ("monthly_count", models.PositiveIntegerField(default=0)),
                ("date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_tracking",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "user_usage_tracking",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="user_usage__user_id_87bb44_idx"
                    ),
                    models.Index(
                        fields=["usage_type", "date"],
                        name="user_usage__usage_t_132e4b_idx",
                    ),
                ],
                "unique_together": {("user", "usage_type", "date")},
            },
        ),
        migrations.CreateModel(
            name="ProfileFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("collaboration", "Collaboration Feedback"),
                            ("portfolio", "Portfolio Feedback"),
                            ("communication", "Communication Feedback"),
                            ("professionalism", "Professionalism"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=1000)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_feedback_received",
                        to="accounts.creatorprofile",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_feedback_given",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ai_profile_feedback",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reviewee", "rating"],
                        name="ai_profile__reviewe_f99963_idx",
                    ),
                    models.Index(
                        fields=["feedback_type"], name="ai_profile__feedbac_394c24_idx"
                    ),
                ],
                "unique_together": {("reviewer", "reviewee", "feedback_type")},
            },
        ),
        migrations.AddIndex(
            model_name="matchresult",
            index=models.Index(
                fields=["requester", "status"], name="match_resul_request_021a8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchresult",
            index=models.Index(
                fields=["matched_creator", "status"],
                name="match_resul_matched_75adcc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matchresult",
            index=models.Index(
                fields=["similarity_score"], name="match_resul_similar_1c8392_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchresult",
            index=models.Index(
                fields=["compatibility_score"], name="match_resul_compati_841d14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchresult",
            index=models.Index(
                fields=["created_at"], name="match_resul_created_812d96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchresult",
            index=models.Index(
                fields=["expires_at"], name="match_resul_expires_9e1cde_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matchresult",
            unique_together={("requester", "matched_creator", "created_at")},
        ),
        migrations.AddIndex(
            model_name="matchhistory",
            index=models.Index(
                fields=["user", "created_at"], name="match_histo_user_id_c342a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchhistory",
            index=models.Index(
                fields=["request_type"], name="match_histo_request_653422_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchhistory",
            index=models.Index(
                fields=["processing_time_ms"], name="match_histo_process_a4f42f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchhistory",
            index=models.Index(
                fields=["created_at"], name="match_histo_created_f174ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchfeedback",
            index=models.Index(
                fields=["match_result"], name="match_feedb_match_r_966b50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchfeedback",
            index=models.Index(fields=["user"], name="match_feedb_user_id_410d05_idx"),
        ),
        migrations.AddIndex(
            model_name="matchfeedback",
            index=models.Index(fields=["rating"], name="match_feedb_rating_c73185_idx"),
        ),
        migrations.AddIndex(
            model_name="matchfeedback",
            index=models.Index(
                fields=["created_at"], name="match_feedb_created_757943_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matchfeedback",
            unique_together={("match_result", "user", "feedback_type")},
        ),
        migrations.AddIndex(
            model_name="generatedcontent",
            index=models.Index(
                fields=["request", "version"], name="generated_c_request_e75251_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedcontent",
            index=models.Index(
                fields=["user_rating", "quality_score"],
                name="generated_c_user_ra_0bf17d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedcontent",
            index=models.Index(
                fields=["is_published", "is_favorite"],
                name="generated_c_is_publ_270d49_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="creatorembedding",
            index=models.Index(
                fields=["creator"], name="creator_emb_creator_3839d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creatorembedding",
            index=models.Index(
                fields=["embedding_version"], name="creator_emb_embeddi_84d295_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creatorembedding",
            index=models.Index(
                fields=["updated_at"], name="creator_emb_updated_9aeb18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentvalidation",
            index=models.Index(
                fields=["is_valid", "confidence_score"],
                name="content_val_is_vali_72c5a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentvalidation",
            index=models.Index(fields=["status"], name="content_val_status_d7c5c5_idx"),
        ),
        migrations.AddIndex(
            model_name="contenttemplate",
            index=models.Index(
                fields=["creator", "template_type"],
                name="content_tem_creator_30ac2d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contenttemplate",
            index=models.Index(
                fields=["content_type", "is_public"],
                name="content_tem_content_e66808_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contenttemplate",
            index=models.Index(
                fields=["is_featured", "usage_count"],
                name="content_tem_is_feat_f88652_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentgenerationrequest",
            index=models.Index(
                fields=["user", "status"], name="content_gen_user_id_562395_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentgenerationrequest",
            index=models.Index(
                fields=["content_type", "platform"],
                name="content_gen_content_62a187_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentgenerationrequest",
            index=models.Index(
                fields=["created_at"], name="content_gen_created_a3dc07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aicontentgeneration",
            index=models.Index(
                fields=["profile", "generation_type"],
                name="ai_content__profile_186f17_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aicontentgeneration",
            index=models.Index(fields=["status"], name="ai_content__status_fa7d14_idx"),
        ),
    ]
