# Generated by Django 4.2.16 on 2025-08-16 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0004_approvalcode"),
        ("ai_services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIContentGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "generation_type",
                    models.CharField(
                        choices=[
                            ("music", "Music Generation"),
                            ("lyrics", "Lyrics Generation"),
                            ("artwork", "Artwork Generation"),
                            ("story", "Story Generation"),
                            ("concept", "Concept Development"),
                            ("bio", "Profile Bio"),
                            ("description", "Project Description"),
                            ("caption", "Social Media Caption"),
                            ("script", "Video Script"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField(max_length=2000)),
                ("parameters", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("generated_content", models.TextField(blank=True)),
                ("quality_score", models.FloatField(default=0.0)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ai_content_generations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfileFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("collaboration", "Collaboration Feedback"),
                            ("portfolio", "Portfolio Feedback"),
                            ("communication", "Communication Feedback"),
                            ("professionalism", "Professionalism"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=1000)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_profile_feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="aigeneratedcontent",
            name="creator",
        ),
        migrations.AlterModelOptions(
            name="contentvalidation",
            options={"ordering": ["-validated_at"]},
        ),
        migrations.RemoveIndex(
            model_name="contentvalidation",
            name="content_val_content_dc07f9_idx",
        ),
        migrations.RemoveIndex(
            model_name="contentvalidation",
            name="content_val_validat_a48bec_idx",
        ),
        migrations.RenameField(
            model_name="contentvalidation",
            old_name="created_at",
            new_name="validated_at",
        ),
        migrations.RemoveField(
            model_name="contentvalidation",
            name="content_id",
        ),
        migrations.RemoveField(
            model_name="contentvalidation",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="contentvalidation",
            name="feedback",
        ),
        migrations.RemoveField(
            model_name="contentvalidation",
            name="model_version",
        ),
        migrations.RemoveField(
            model_name="contentvalidation",
            name="validation_score",
        ),
        migrations.RemoveField(
            model_name="contentvalidation",
            name="validation_type",
        ),
        migrations.AddField(
            model_name="contentvalidation",
            name="confidence_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="contentvalidation",
            name="issues",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="contentvalidation",
            name="portfolio_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validation",
                to="accounts.portfolioitem",
            ),
        ),
        migrations.AddField(
            model_name="contentvalidation",
            name="recommendations",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="contentvalidation",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contentvalidation",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentvalidation",
            name="status",
            field=models.CharField(
                choices=[
                    ("valid", "Valid"),
                    ("invalid", "Invalid"),
                    ("flagged", "Flagged for Review"),
                    ("pending", "Pending Review"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contentvalidation",
            name="validation_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name="contentvalidation",
            index=models.Index(
                fields=["is_valid", "confidence_score"],
                name="content_val_is_vali_72c5a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentvalidation",
            index=models.Index(fields=["status"], name="content_val_status_d7c5c5_idx"),
        ),
        migrations.DeleteModel(
            name="AIGeneratedContent",
        ),
        migrations.AddField(
            model_name="profilefeedback",
            name="reviewee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_feedback_received",
                to="accounts.creatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="profilefeedback",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_feedback_given",
                to="accounts.creatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="aicontentgeneration",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_generations",
                to="accounts.creatorprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="profilefeedback",
            index=models.Index(
                fields=["reviewee", "rating"], name="ai_profile__reviewe_f99963_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profilefeedback",
            index=models.Index(
                fields=["feedback_type"], name="ai_profile__feedbac_394c24_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="profilefeedback",
            unique_together={("reviewer", "reviewee", "feedback_type")},
        ),
        migrations.AddIndex(
            model_name="aicontentgeneration",
            index=models.Index(
                fields=["profile", "generation_type"],
                name="ai_content__profile_186f17_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aicontentgeneration",
            index=models.Index(fields=["status"], name="ai_content__status_fa7d14_idx"),
        ),
    ]
