# Generated by Django 4.2.16 on 2025-08-20 09:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_premiumaddon_subscriptionplan_usersubscription_and_more"),
        ("ai_services", "0002_aicontentgeneration_profilefeedback_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentGenerationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("social_media_post", "Social Media Post"),
                            ("video_script", "Video Script"),
                            ("blog_post", "Blog Post"),
                            ("marketing_copy", "Marketing Copy"),
                            ("creative_writing", "Creative Writing"),
                            ("product_description", "Product Description"),
                            ("email_campaign", "Email Campaign"),
                            ("press_release", "Press Release"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("twitter", "Twitter"),
                            ("linkedin", "LinkedIn"),
                            ("facebook", "Facebook"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField(max_length=2000)),
                ("topic", models.CharField(max_length=200)),
                ("target_audience", models.CharField(blank=True, max_length=200)),
                ("tone", models.CharField(blank=True, max_length=50)),
                ("word_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.PositiveIntegerField(default=1000)),
                ("custom_parameters", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                (
                    "cost_estimate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_requests",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "content_generation_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, max_length=300)),
                ("color", models.CharField(default="#007bff", max_length=7)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="ai_services.contentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Content Categories",
                "db_table": "content_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserUsageTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("content_generation", "Content Generation"),
                            ("template_usage", "Template Usage"),
                            ("api_call", "API Call"),
                        ],
                        max_length=30,
                    ),
                ),
                ("tokens_consumed", models.PositiveIntegerField(default=0)),
                (
                    "cost_incurred",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("daily_count", models.PositiveIntegerField(default=0)),
                ("monthly_count", models.PositiveIntegerField(default=0)),
                ("date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_tracking",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "user_usage_tracking",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="user_usage__user_id_87bb44_idx"
                    ),
                    models.Index(
                        fields=["usage_type", "date"],
                        name="user_usage__usage_t_132e4b_idx",
                    ),
                ],
                "unique_together": {("user", "usage_type", "date")},
            },
        ),
        migrations.CreateModel(
            name="GeneratedContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("title", models.CharField(blank=True, max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("quality_score", models.FloatField(default=0.0)),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ],
                        null=True,
                    ),
                ),
                ("user_feedback", models.TextField(blank=True, max_length=1000)),
                ("is_published", models.BooleanField(default=False)),
                ("is_favorite", models.BooleanField(default=False)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_versions",
                        to="ai_services.generatedcontent",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_content",
                        to="ai_services.contentgenerationrequest",
                    ),
                ),
            ],
            options={
                "db_table": "generated_content",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["request", "version"],
                        name="generated_c_request_e75251_idx",
                    ),
                    models.Index(
                        fields=["user_rating", "quality_score"],
                        name="generated_c_user_ra_0bf17d_idx",
                    ),
                    models.Index(
                        fields=["is_published", "is_favorite"],
                        name="generated_c_is_publ_270d49_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=500)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("prompt", "Prompt Template"),
                            ("structure", "Content Structure"),
                            ("style", "Style Guide"),
                            ("format", "Format Template"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("social_media_post", "Social Media Post"),
                            ("video_script", "Video Script"),
                            ("blog_post", "Blog Post"),
                            ("marketing_copy", "Marketing Copy"),
                            ("creative_writing", "Creative Writing"),
                            ("product_description", "Product Description"),
                            ("email_campaign", "Email Campaign"),
                            ("press_release", "Press Release"),
                        ],
                        max_length=30,
                    ),
                ),
                ("prompt_template", models.TextField()),
                ("default_parameters", models.JSONField(blank=True, default=dict)),
                ("example_output", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_templates",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "content_templates",
                "ordering": ["-usage_count", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["creator", "template_type"],
                        name="content_tem_creator_30ac2d_idx",
                    ),
                    models.Index(
                        fields=["content_type", "is_public"],
                        name="content_tem_content_e66808_idx",
                    ),
                    models.Index(
                        fields=["is_featured", "usage_count"],
                        name="content_tem_is_feat_f88652_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="contentgenerationrequest",
            index=models.Index(
                fields=["user", "status"], name="content_gen_user_id_562395_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentgenerationrequest",
            index=models.Index(
                fields=["content_type", "platform"],
                name="content_gen_content_62a187_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentgenerationrequest",
            index=models.Index(
                fields=["created_at"], name="content_gen_created_a3dc07_idx"
            ),
        ),
    ]
