# Generated by Django 4.2.16 on 2025-09-15 07:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_premiumaddon_subscriptionplan_usersubscription_and_more"),
        ("ai_services", "0003_contentgenerationrequest_contentcategory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(help_text="Cosine similarity score (0-1)"),
                ),
                (
                    "compatibility_score",
                    models.FloatField(help_text="Overall compatibility score (0-100)"),
                ),
                (
                    "match_reasons",
                    models.JSONField(
                        default=list, help_text="List of reasons for the match"
                    ),
                ),
                (
                    "shared_skills",
                    models.JSONField(default=list, help_text="Skills in common"),
                ),
                (
                    "complementary_skills",
                    models.JSONField(default=list, help_text="Complementary skills"),
                ),
                (
                    "match_type",
                    models.CharField(
                        default="general",
                        help_text="Type of match (collaboration, mentorship, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "match_filters",
                    models.JSONField(
                        default=dict, help_text="Filters used for matching"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("viewed", "Viewed"),
                            ("interested", "Interested"),
                            ("contacted", "Contacted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "matched_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_matches",
                        to="accounts.creatorprofile",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_requests",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "match_results",
                "ordering": ["-compatibility_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("find_matches", "Find Matches"),
                            ("batch_match", "Batch Match"),
                            ("similar_creators", "Similar Creators"),
                            ("collaboration_match", "Collaboration Match"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "filters_used",
                    models.JSONField(
                        default=dict, help_text="Filters applied to the search"
                    ),
                ),
                ("results_count", models.PositiveIntegerField(default=0)),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(
                        help_text="Processing time in milliseconds"
                    ),
                ),
                ("embedding_version", models.CharField(default="v1.0", max_length=50)),
                ("top_similarity_score", models.FloatField(blank=True, null=True)),
                ("average_compatibility", models.FloatField(blank=True, null=True)),
                ("matches_viewed", models.PositiveIntegerField(default=0)),
                ("matches_contacted", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_history",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "match_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("quality", "Match Quality"),
                            ("relevance", "Relevance"),
                            ("accuracy", "Accuracy"),
                            ("usefulness", "Usefulness"),
                        ],
                        default="quality",
                        max_length=20,
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Optional feedback comment"),
                ),
                ("contacted_match", models.BooleanField(default=False)),
                ("collaboration_started", models.BooleanField(default=False)),
                ("would_recommend", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="ai_services.matchresult",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "match_feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreatorEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "embedding_vector",
                    models.JSONField(
                        help_text="Vector representation of creator profile"
                    ),
                ),
                ("embedding_version", models.CharField(default="v1.0", max_length=50)),
                (
                    "skills_hash",
                    models.CharField(
                        help_text="Hash of skills data used", max_length=64
                    ),
                ),
                (
                    "bio_hash",
                    models.CharField(help_text="Hash of bio data used", max_length=64),
                ),
                (
                    "interests_hash",
                    models.CharField(
                        help_text="Hash of interests data used", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_profile_update", models.DateTimeField(blank=True, null=True)),
                (
                    "creator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="accounts.creatorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "creator_embeddings",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="matchresult",
            index=models.Index(
                fields=["requester", "status"], name="match_resul_request_021a8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchresult",
            index=models.Index(
                fields=["matched_creator", "status"],
                name="match_resul_matched_75adcc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matchresult",
            index=models.Index(
                fields=["similarity_score"], name="match_resul_similar_1c8392_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchresult",
            index=models.Index(
                fields=["compatibility_score"], name="match_resul_compati_841d14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchresult",
            index=models.Index(
                fields=["created_at"], name="match_resul_created_812d96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchresult",
            index=models.Index(
                fields=["expires_at"], name="match_resul_expires_9e1cde_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matchresult",
            unique_together={("requester", "matched_creator", "created_at")},
        ),
        migrations.AddIndex(
            model_name="matchhistory",
            index=models.Index(
                fields=["user", "created_at"], name="match_histo_user_id_c342a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchhistory",
            index=models.Index(
                fields=["request_type"], name="match_histo_request_653422_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchhistory",
            index=models.Index(
                fields=["processing_time_ms"], name="match_histo_process_a4f42f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchhistory",
            index=models.Index(
                fields=["created_at"], name="match_histo_created_f174ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchfeedback",
            index=models.Index(
                fields=["match_result"], name="match_feedb_match_r_966b50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchfeedback",
            index=models.Index(fields=["user"], name="match_feedb_user_id_410d05_idx"),
        ),
        migrations.AddIndex(
            model_name="matchfeedback",
            index=models.Index(fields=["rating"], name="match_feedb_rating_c73185_idx"),
        ),
        migrations.AddIndex(
            model_name="matchfeedback",
            index=models.Index(
                fields=["created_at"], name="match_feedb_created_757943_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matchfeedback",
            unique_together={("match_result", "user", "feedback_type")},
        ),
        migrations.AddIndex(
            model_name="creatorembedding",
            index=models.Index(
                fields=["creator"], name="creator_emb_creator_3839d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creatorembedding",
            index=models.Index(
                fields=["embedding_version"], name="creator_emb_embeddi_84d295_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creatorembedding",
            index=models.Index(
                fields=["updated_at"], name="creator_emb_updated_9aeb18_idx"
            ),
        ),
    ]
