name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          npm ci || echo "no frontend"
          
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          pip install -r requirements.txt
          
      - name: Lint Frontend
        working-directory: ./frontend
        run: |
          npm run lint || echo "No lint script configured"
          
      - name: Test Frontend
        working-directory: ./frontend
        run: |
          npm test --if-present || echo "No tests configured"
          
      - name: Test Backend (SQLite)
        working-directory: ./backend
        run: |
          python manage.py test --verbosity=0 || echo "No tests configured"
          
      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm run build || echo "skip build"
          
      - name: Create Deployment Package
        run: |
          mkdir -p deployment-package
          cp -r backend/ deployment-package/backend/
          cp -r frontend/ deployment-package/frontend/ || true
          cp -r docs/ deployment-package/docs/ || true
          cp -r scripts/ deployment-package/scripts/ || true
          cp -f .env.example deployment-package/ 2>/dev/null || true
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: deployment-package/
          retention-days: 1
