name: Deploy UAT

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [ "develop" ]

jobs:
  deploy-uat:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./deployment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        working-directory: ./deployment
        run: |
          cd frontend && npm ci
          cd ../backend && pip install -r requirements.txt
          
      - name: Run Database Migrations
        working-directory: ./deployment/backend
        env:
          DATABASE_URL: ${{ secrets.UAT_DB_URL }}
          GIT_SHA: ${{ github.sha }}
        run: |
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput
          
      - name: Health Check
        working-directory: ./backend
        env:
          DATABASE_URL: ${{ secrets.UAT_DB_URL }}
        run: |
          python manage.py check --deploy
          
      - name: Deploy to UAT Environment
        env:
          DATABASE_URL: ${{ secrets.UAT_DB_URL }}
          GIT_SHA: ${{ github.sha }}
        run: |
          echo "Deploying Creator Community Platform to UAT..."
          echo "Frontend build completed"
          echo "Backend migrations applied"
          echo "Health checks passed"
          echo "UAT deployment ready"
          # TODO: Add actual deployment commands (Docker, cloud CLI, etc.)
          
      - name: Output UAT URL
        run: |
          echo "UAT_URL=https://uat-creator-platform.example.com" >> $GITHUB_OUTPUT
          echo "🚀 UAT Deployment Complete!"
